"""empty message

Revision ID: 8f9c903c9f7d
Revises: 3d7c44f04abc
Create Date: 2022-03-24 23:52:41.619743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9c903c9f7d'
down_revision = '3d7c44f04abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('avatar_image', sa.String(), nullable=True),
    sa.Column('plain_password', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_nickname'), ['nickname'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.drop_index('ix_user_nickname')
        batch_op.drop_column('avatar_image')
        batch_op.drop_column('plain_password')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('plain_password', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar_image', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_user_nickname', ['nickname'], unique=False)
        batch_op.drop_column('type')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_nickname'))

    op.drop_table('student')
    # ### end Alembic commands ###
