"""empty message

Revision ID: abf6c1d6ebb2
Revises: 
Create Date: 2022-03-20 14:46:26.831653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf6c1d6ebb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('reward', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounty_description'), 'bounty', ['description'], unique=True)
    op.create_index(op.f('ix_bounty_title'), 'bounty', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bounty_title'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_description'), table_name='bounty')
    op.drop_table('bounty')
    # ### end Alembic commands ###
