"""empty message

Revision ID: df70fd061aff
Revises: 8f9c903c9f7d
Create Date: 2022-03-25 00:03:06.558920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df70fd061aff'
down_revision = '8f9c903c9f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_bounty_theme'), ['theme'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bounty_theme'))
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
